# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-04-02 20:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_squashed_0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='store',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='store.Store'),
        ),
    ]
