# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-04-02 21:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
        ('store', '0003_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customers',
            field=models.ManyToManyField(to='registration.MyUser'),
        ),
    ]
